version: '3'
services:
  webserver:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./letsencrypt/:/etc/letsencrypt/
    ports:
    - "80:80"
    container_name: webserver
  odtcs-screen:
    build: ./screen/
    container_name: odtcs-screen
    expose:
    - "80"
  odtcs-workshop-hack:
    build: ./workshop-hack/
    container_name: odtcs-workshop-hack
    expose:
    - "80"
